### ISSUE TITLE
EsLint

### ISSUE THREAD

**Issue by rustemginiyatullin** [fs/backbone-base#94]
http://eslint.org

**Comment by rustemginiyatullin** [comment]
@maratfakhreev what do you think?

**Comment by maratfakhreev** [comment]
@rustemginiyatullin really good tool which I want add in the near future. But if you create PR with this one and with some small configuration for the first time it will be awesome.)

**Comment by maratfakhreev** [comment]
#102

**Comment by maratfakhreev** [comment]
#102
